### PR TITLE
Updated ./bin/pasta_web.py as per current API

### PR DESCRIPTION
**Pull request by ShubhamPandey28**
As Config API has been changed, pasta_web has been updated with those changes.

Signed-off-by: Shubhamkumar Pandey <b18194@students.iitmandi.ac.in>

### CODE REVIEW

**Comment by rralf** [comment]
Cc: @bulwahn 

Hi Shubham,

thanks for picking this up! We didn't use the webinterface for quite a while, and I even thought of removing it. However, did you test your patches? Is it in a working state with your changes?

Thanks!

**Comment by ShubhamPandey28** [comment]
Yes and It is still in working state, I did manual testing with different type of commits, single thread and multithread patches

**Comment by ShubhamPandey28** [comment]
Here is the proof of working.

Screenshot from 2020-07-22 16-48-13

**Comment by rralf** [comment]
Cool, prefect! Rebased and merged to next. Thanks!

**Pull request closed without merging**
