### PR TITLE
Detect and visualise mismatch

### LINKED ISSUE #20: Determine who picks up patches to certain files vs. who is the documented maintainer in MAINTAINERS
Motivation:

This would allow to show to which extent the MAINTAINERS file reflects the current practice and the mismatch.

Open question:
Does this even need the mailing list, or could this be determined just by considering the git history, i.e., the git committer of each commit and the MAINTAINERS file?

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Fixes #20 

- [x] Write a file having the list of git kernel trees.
- [x] Write a function which finds the committer name and info +  calls `./scripts/get_maintainer.pl <file_name>` for the patch.
- [x] Write a function which creates a file having the mismatch
- [ ] Run all over mainline kernel tree
- [ ] Create a plot using panda library (human readable format or useful results)
- [ ] Add a command line argument in pasta.

Please find more info below:

pasta

### CODE REVIEW

**Review by bulwahn — COMMENTED** [review]
The script still looks incomplete; I guess you are still working on this.

Did you actually run the commands you invoke on a few commits yet and looked at the commands output? 

`get_maintainer.pl` provides multiple developers as output, the committer is actually the maintainer to commit it to the git repository, but the Signed-off chain might indicate further maintainers of smaller subsystems.

I believe at the moment, the best definition of a mismatch and use of the git metadata and the maintainer information is not fully clear to anyone and requires some investigation.

However, during this investigation, the data and its evaluation will show the best definition and use of the git metadata and the maintainer information to actually determine a meaningful mismatch that indicates the need for action.

On the technical side:

I do not think it is good to include the get_maintainer.pl script in pasta. It is available in the kernel repository (which is pulled in as submodule), so why create a clone here?#

There are a few further issues in the code, but I will comment on those once the script is getting more complete.

**Comment by tapaswenipathak** [comment]
@bulwahn Sure, I will loop you after I finish all the tasks.

**Comment by tapaswenipathak** [comment]
Thanks for the brain dump; the PR is in draft state, I appreciate your comments, I will tag for review.

**Comment by rralf** [comment]
Hi Tapasweni,

thanks for the draft! Please try to align with other PaStA tools. I'd like to start tools with ./pasta toolname arguments.

Last week, I implemented a MAINTAINERS interface for PaStA. Please try to use it instead of calling get_maintainers.pl (it's known to be pretty slow). I'm happy to accept patches for the interface (I'm sure there are still some incomplete or odd things).

Thanks
  Ralf

**Comment by rralf** [comment]
Ah, I forgot one thing: You need to use the MAINTAINERS file at the moment the commit was accepted, as the MAINTAINERS underlies frequent changes.

This makes things a bit harder. It should be good enough if look at the MAINTAINERS file of the closest release. Here https://github.com/lfd/PaStA/commit/1d6dfd0f45c5f9adaaac81bfa60e889dcdb5c973#diff-1d0541a8ccacc43136fd8d7eb48424c6R401 you can find an example how we load the maintainers file (please ignore the rest of the code, this is a WIP branch).

**Comment by tapaswenipathak** [comment]
Hi @rralf:

Just getting hang of the project for tackling with everything else. Thanks for the brain dump, appreciate your comments; I will tag for review.

**Pull request closed without merging**
