### PR TITLE
[WIP] Patchwork integration

### PR DESCRIPTION
**Pull request by rsarky**
This is a clone of #31 but additionally rebased on the `next` branch

### CODE REVIEW

**Comment by rralf** [comment]
Hi Rohit. I won't integrate this to next - at the moment. But I will integrate Mete's patches to the wip-patchwork-integration branch.

**Comment by rralf** [comment]
Thanks, merged to wip-patchwork-integration.

**Comment by rralf** [comment]
What the heck, now it pulled it to next -.- Sigh...

**Comment by rralf** [comment]
Ok, so for the future... Don't be surprised if the web interface tells you that I didn't accept your pull request. We can still use the interface for discussion and reviews, but I will do the integration steps manually by hand. I can really understand why people still stick to mail-based development processes...

**Comment by rsarky** [comment]
> Hi Rohit. I won't integrate this to next - at the moment. But I will integrate Mete's patches to the wip-patchwork-integration branch.

Oh this wasn't meant for integration now. I just wanted a fresh up to date branch that I could work with. But it's okay that you made another branch. Wouldnt it be better if this stayed as a PR? Otherwise I will need permissions to push to the wip-patchwork-integration branch

**Comment by rralf** [comment]
It's a good idea to have Mete's patches in a wip branch. Just to ensure that we don't loose them. Other than that, let me check if I can give you permissions to a specific branch...

**Comment by rsarky** [comment]
> It's a good idea to have Mete's patches in a wip branch. Just to ensure that we don't loose them. Other than that, let me check if I can give you permissions to a specific branch...

Or I could submit PRs to this new wip branch

**Comment by rsarky** [comment]
Idk if that would be the best way to go about it.
I was thinking instead of the integration being a whole lot of patches being merged at once,
I could incrementally merge relatively independent patch sets into PaStA

**Pull request merged**
